# app.py — AUTO-GENERATED by make_office.py
# Office: news_editor
# Open office — import news_editor to use in a larger network.
#
#   from gallery.org_two_office_news.news_editor.app import news_editor

import json

from dissyslab.composed_agent import composed_agent
from dissyslab.blocks import Sink
from dissyslab.blocks.role import Role
from dissyslab.components.transformers.ai_agent import ai_agent
from dissyslab.components.sinks.discard import Discard

# ── Sinks ────────────────────────────────────────────────────────────

_discard = Discard()
discard = Sink(fn=_discard.run, name="discard")

# ── Role: editor ──────────────────────────────────────────────────────

_editor_prompt = "# Role: editor\n\nYou are a news editor who receives articles and sends\narticles to a rewriter or a discard.\n\nYour job is to route each article by topic. Add a \"topic\"\nfield with one of: politics, economics, technology, science,\nenvironment, conflict, other.\n\nIf the topic is politics, economics, technology, science,\nenvironment, or conflict, send to rewriter.\nOtherwise send to discard.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: rewriter, discard>\", \"text\": \"<content>\"}"
_editor_ai = ai_agent(_editor_prompt)

def editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw         = _editor_ai(text)
        result      = raw if isinstance(raw, dict) else json.loads(raw)
        out         = {**msg, **result}
        destination = result.get("send_to", "rewriter")
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f"[editor] Error: {e}")
        return []


# ── Role: rewriter ────────────────────────────────────────────────────

_rewriter_prompt = "# Role: rewriter\n\nYou are a news rewriter who receives articles and sends\narticles to an output.\n\nYour job is to rewrite each article as a crisp one-paragraph\nbriefing note. Begin with the significance rating from the\n\"significance\" field if present. Write clearly and concisely\nfor a busy reader. Put your rewritten text in the \"text\" field.\nPreserve the source, url, topic, and significance fields.\n\nAlways send to output.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: output>\", \"text\": \"<content>\"}"
_rewriter_ai = ai_agent(_rewriter_prompt)

def rewriter_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw         = _rewriter_ai(text)
        result      = raw if isinstance(raw, dict) else json.loads(raw)
        out         = {**msg, **result}
        destination = result.get("send_to", "output")
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f"[rewriter] Error: {e}")
        return []


# ── Agents ───────────────────────────────────────────────────────────

Jordan = Role(
    fn=editor_fn,
    statuses=["rewriter", "discard"],
    name="Jordan",
)
Riley = Role(
    fn=rewriter_fn,
    statuses=["output"],
    name="Riley",
)

# ── Composed Agent ───────────────────────────────────────────────────

news_editor = composed_agent(
    name="news_editor",
    inputs=["article_in"],
    outputs=["article_out"],
)

news_editor.network = [
    (news_editor.article_in, Jordan),
    (Jordan.out_0, Riley),  # rewriter
    (Jordan.out_1, discard),  # discard
    (Riley.out_0, news_editor.article_out),  # output
]
