# dissyslab/gallery/apps/mac_speed_suite/make_report.py
"""
DEPRECATED -- report.html is now produced by the office itself.

The report is generated by the `report_html` sink (sinks/report_html_sink.py),
wired into office.md and fed by the EVALUATOR's real message. Run:

    dsl run .

in this folder, which writes report.html and always matches what `dsl run`
prints -- including any strategy you add. This shim stays only so old
instructions that call `python3 make_report.py` still point the right way; it
no longer keeps its own private copy of the pipeline, which used to drift from
office.md whenever a strategy was added (the report/console divergence bug).
"""

import sys

if __name__ == "__main__":
    sys.stderr.write(
        "make_report.py is deprecated: report.html is now produced by the "
        "office's report_html sink.\nRun `dsl run .` in this folder instead.\n"
    )
    sys.exit(1)
