# app.py — AUTO-GENERATED by make_network.py
# Network: two_office_news

# Topology:
#   al_jazeera  →  news_monitor.article_in
#   bbc_world  →  news_monitor.article_in
#   npr_news  →  news_monitor.article_in
#   news_monitor.article_out  →  news_editor.article_in
#   news_editor.article_out  →  intelligence_display


from dissyslab import network
from dissyslab.blocks import Source, Sink
from dissyslab.components.sources.rss_normalizer import al_jazeera, bbc_world, npr_news
from dissyslab.components.sinks.intelligence_display import IntelligenceDisplay

from gallery.org_two_office_news.news_monitor.app import news_monitor
from gallery.org_two_office_news.news_editor.app import news_editor


# ── Sources ──────────────────────────────────────────────────────────

_al_jazeera = al_jazeera(max_articles=4)
src_al_jazeera = Source(fn=_al_jazeera.run, name="al_jazeera")

_bbc_world = bbc_world(max_articles=4)
src_bbc_world = Source(fn=_bbc_world.run, name="bbc_world")

_npr_news = npr_news(max_articles=4)
src_npr_news = Source(fn=_npr_news.run, name="npr_news")


# ── Sinks ────────────────────────────────────────────────────────────

_intelligence_display = IntelligenceDisplay()
intelligence_display = Sink(
    fn=_intelligence_display.run, name="intelligence_display")


# ── Network ──────────────────────────────────────────────────────────

g = network([
    (src_al_jazeera, news_monitor.article_in),
    (src_bbc_world, news_monitor.article_in),
    (src_npr_news, news_monitor.article_in),
    (news_monitor.article_out, news_editor.article_in),
    (news_editor.article_out, intelligence_display),
])


if __name__ == "__main__":
    print()
    print("Two Office News")
    print("=" * 60)
    print()
    g.run_network(timeout=360)
    print()
    print("Done!")
    print()
