# make_office.py
#
# Compiles an open office into app.py — a Python file exporting
# a composed_agent instance importable by larger networks.
#
# An open office has Inputs and Outputs declared in office.md.
# It is a composable black box, not a standalone runnable network.
#
# Usage:
#   python3 make_office.py gallery/news_monitor/
#
# For closed (runnable) offices, use office_compiler.py instead.

import sys
import json
from pathlib import Path

from office_utils import (
    SOURCE_REGISTRY,
    SINK_REGISTRY,
    parse_roles,
    parse_office,
    validate,
    show_routing_table,
)


# ── Write app.py ──────────────────────────────────────────────────────────────

def write_app(roles, office, office_dir):
    """
    Write app.py for an open office.
    Exports a composed_agent instance with named inports and outports.
    """
    office_path = Path(office_dir)
    app_path = office_path / "app.py"
    office_name = office["office_name"]
    inputs = office["inputs"]
    outputs = office["outputs"]

    known_agents = {a["name"] for a in office["agents"]}
    known_outputs = set(outputs)

    # Port index: role_name → {destination_name → out_N index}
    port_index = {
        role_name: {dest: i for i, dest in enumerate(role["sends_to"])}
        for role_name, role in roles.items()
    }

    lines = []

    # ── Imports ───────────────────────────────────────────────────────────────

    rss_sources = [
        s["name"] for s in office["sources"]
        if SOURCE_REGISTRY.get(s["name"], {}).get("type") == "rss"
    ]
    bluesky_sources = [
        s for s in office["sources"]
        if SOURCE_REGISTRY.get(s["name"], {}).get("type") == "bluesky"
    ]
    sink_imports = sorted({
        SINK_REGISTRY[s["name"]]["import"]
        for s in office["sinks"]
    })
    bluesky_imports = [
        SOURCE_REGISTRY[s["name"]]["import"]
        for s in bluesky_sources
    ]

    lines += [
        f"# app.py — AUTO-GENERATED by make_office.py",
        f"# Office: {office_name}",
        f"# Open office — import {office_name} to use in a larger network.",
        f"",
        f"import json",
        f"",
        f"from dsl.composed_agent import composed_agent",
        f"from dsl.blocks.role import Role",
        f"from components.transformers.ai_agent import ai_agent",
    ]
    if rss_sources:
        lines += [
            "from components.sources.rss_normalizer import " +
            ", ".join(rss_sources)
        ]
    lines += bluesky_imports + sink_imports + ["", ""]

    # ── Role functions ────────────────────────────────────────────────────────

    for role_name, role in roles.items():
        role_text = open(office_path / "roles" / f"{role_name}.md").read()
        valid_dests = role["sends_to"]
        default_dest = valid_dests[0]
        contract = (
            f'\nReturn JSON only, no explanation, no nested JSON:\n'
            f'{{"send_to": "<one of: {", ".join(valid_dests)}>", '
            f'"text": "<content>"}}'
        )
        prompt = role_text.strip() + "\n" + contract

        lines += [
            f"# ── Role: {role_name} " + "─" * (60 - len(role_name)),
            f"",
            f"_{role_name}_prompt = {json.dumps(prompt)}",
            f"_{role_name}_ai = ai_agent(_{role_name}_prompt)",
            f"",
            f"def {role_name}_fn(msg):",
            f"    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)",
            f"    try:",
            f"        raw         = _{role_name}_ai(text)",
            f"        result      = raw if isinstance(raw, dict) else json.loads(raw)",
            f"        out         = {{**msg, **result}}",
            f'        destination = result.get("send_to", "{default_dest}")',
            f"        if isinstance(destination, list):",
            f"            return [(out, dest) for dest in destination]",
            f"        return [(out, destination)]",
            f"    except Exception as e:",
            f'        print(f"[{role_name}] Error: {{e}}")',
            f"        return []",
            f"",
            f"",
        ]

    # ── Role nodes ────────────────────────────────────────────────────────────

    lines += ["# ── Agents " + "─" * 59, ""]
    for agent in office["agents"]:
        agent_name = agent["name"]
        role_name = agent["role"]
        lines += [
            f'{agent_name} = Role(',
            f'    fn={role_name}_fn,',
            f'    statuses={json.dumps(roles[role_name]["sends_to"])},',
            f'    name="{agent_name}",',
            f')',
        ]
    lines += ["", ""]

    # ── Composed agent ────────────────────────────────────────────────────────

    lines += [
        "# ── Composed Agent " + "─" * 51,
        "",
        f"{office_name} = composed_agent(",
        f'    name="{office_name}",',
        f"    inputs={json.dumps(inputs)},",
        f"    outputs={json.dumps(outputs)},",
        f")",
        "",
    ]

    # ── Edges ─────────────────────────────────────────────────────────────────

    edge_lines = []

    for conn in office["connections"]:
        sender = conn["from"]
        if conn["destination"] == "destination" and sender in set(inputs):
            edge_lines.append(
                f"    ({office_name}.{sender}, {conn['to'][0]}),")

    for conn in office["connections"]:
        sender = conn["from"]
        dest_name = conn["destination"]
        if dest_name == "destination" or sender not in known_agents:
            continue
        agent = next(a for a in office["agents"] if a["name"] == sender)
        role_name = agent["role"]
        idx = port_index[role_name].get(dest_name)
        if idx is None:
            continue
        for to in conn["to"]:
            if to == "discard":
                continue
            if to in known_outputs:
                edge_lines.append(
                    f"    ({sender}.out_{idx}, {office_name}.{to}),  # {dest_name}"
                )
            else:
                edge_lines.append(
                    f"    ({sender}.out_{idx}, {to}),  # {dest_name}"
                )

    lines += [f"{office_name}.network = ["]
    lines += edge_lines
    lines += ["]", "", ""]

    app_path.write_text("\n".join(lines))
    print(f"  ✓ Written to {app_path}")
    print()
    print(f"  Import with:")
    print(f"    from gallery.{office_path.name}.app import {office_name}")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 make_office.py gallery/office_name/")
        sys.exit(1)

    office_dir = sys.argv[1]

    print()
    print("Parsing roles...")
    roles = parse_roles(office_dir)

    print()
    print("Parsing office...")
    office = parse_office(office_dir)

    if not (office["inputs"] or office["outputs"]):
        print()
        print("Error: this is a closed office (no Inputs/Outputs).")
        print("Use office_compiler.py instead:")
        print(f"  python3 office_compiler.py {office_dir}")
        sys.exit(1)

    print()
    print("Validating...")
    errors = validate(roles, office)
    if errors:
        print("Errors found:")
        for e in errors:
            print(f"  ✗ {e}")
        sys.exit(1)
    print("  ✓ All checks passed.")

    show_routing_table(roles, office)

    answer = input("Does this look right? (yes / no): ").strip().lower()
    if answer != "yes":
        print()
        print("Edit your role or office files and run the compiler again.")
        sys.exit(0)

    print()
    print("Generating app.py...")
    write_app(roles, office, office_dir)
