# app.py — AUTO-GENERATED by office_compiler.py
# Office: intelligence_briefing
# Roles: analyst, editor
#
# Routing:
#   al_jazeera  →  Alex
#   bbc_world  →  Alex
#   npr_news  →  Alex
#   Alex [editor]  →  Morgan
#   Alex [discard]  →  jsonl_recorder
#   Morgan [archivist]  →  intelligence_display, jsonl_recorder


import json
import re

from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent
from components.sources.rss_normalizer import al_jazeera, bbc_world, npr_news
from components.sinks.intelligence_display import IntelligenceDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder


# ── Logging ──────────────────────────────────────────────────────────

_log_file = open('flow.log', 'w')

def _log(agent, destination, msg):
    line = '─' * 62
    _log_file.write(line + '\n')
    _log_file.write(f' {agent}  →  {destination}\n')
    _log_file.write(line + '\n')
    skip = {'send_to'}
    for k, v in msg.items():
        if k in skip:
            continue
        v_str = str(v)
        if len(v_str) > 80:
            v_str = v_str[:77] + '...'
        _log_file.write(f' {k:<12} {v_str}\n')
    _log_file.write('\n')
    _log_file.flush()


# ── Role: analyst ─────────────────────────────────────────────────────

_analyst_prompt = "# Role: analyst\n\nYou are a news analyst who receives news articles and sends\narticles to an editor or a discard.\n\nYour job is to decide if each article describes a significant\nworld event \u2014 a major political development, conflict, natural\ndisaster, or scientific breakthrough.\n\nIf the article is significant, send to editor.\nOtherwise send to discard.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: editor, discard>\", \"text\": \"<content>\"}"
_analyst_ai = ai_agent(_analyst_prompt)

def analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _analyst_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["editor"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('analyst', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[analyst] Error: {e}")
        return []


# ── Role: editor ──────────────────────────────────────────────────────

_editor_prompt = "# Role: editor\n\nYou are a senior editor who receives news articles and sends\narticles to an archivist.\n\nYour job is to rewrite each article as a crisp one-paragraph\nintelligence briefing note. Begin with a significance rating\non its own line: CRITICAL, HIGH, MEDIUM, or LOW. Then write\none paragraph summarizing the key facts. Preserve the source,\nurl, and title fields from the input message. Put your\nsignificance rating in a field called \"significance\" and your\nsummary in the \"text\" field.\n\nAlways send to archivist.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: archivist>\", \"text\": \"<content>\"}"
_editor_ai = ai_agent(_editor_prompt)

def editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _editor_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["archivist"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('editor', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[editor] Error: {e}")
        return []


# ── Sinks ────────────────────────────────────────────────────────────

_intelligence_display = IntelligenceDisplay()
intelligence_display = Sink(fn=_intelligence_display.run, name="intelligence_display")

_jsonl_recorder = JSONLRecorder(path="briefing.jsonl")
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name="jsonl_recorder")


# ── Sources ──────────────────────────────────────────────────────────

_al_jazeera = al_jazeera(max_articles=5)
src_al_jazeera = Source(fn=_al_jazeera.run, name="al_jazeera")

_bbc_world = bbc_world(max_articles=5)
src_bbc_world = Source(fn=_bbc_world.run, name="bbc_world")

_npr_news = npr_news(max_articles=5)
src_npr_news = Source(fn=_npr_news.run, name="npr_news")


# ── Agents ───────────────────────────────────────────────────────────

Alex = Role(fn=analyst_fn, statuses=["editor", "discard"], name="Alex")
Morgan = Role(fn=editor_fn, statuses=["archivist"], name="Morgan")


# ── Network ──────────────────────────────────────────────────────────

g = network([
    (src_al_jazeera, Alex),
    (src_bbc_world, Alex),
    (src_npr_news, Alex),
    (Alex.out_0, Morgan),  # editor
    (Alex.out_1, jsonl_recorder),  # discard
    (Morgan.out_0, intelligence_display),  # archivist
    (Morgan.out_0, jsonl_recorder),  # archivist
])


if __name__ == "__main__":
    print()
    print("Intelligence Briefing")
    print("=" * 60)
    print()
    g.run_network()
    _log_file.close()
    print()
    print("Done! Flow log written to flow.log")
    print()