# app.py — AUTO-GENERATED by office_compiler.py
# Office: news_filter
# Roles: filter
#
# Routing:
#   al_jazeera  →  Felix
#   bbc_world  →  Felix
#   Felix [keeper]  →  console_printer
#   Felix [discard]  →  jsonl_recorder


import json
import re

from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent
from components.sources.rss_normalizer import al_jazeera, bbc_world
from components.sinks.sink_jsonl_recorder import JSONLRecorder
from components.sinks.console_display import ConsoleDisplay


# ── Logging ──────────────────────────────────────────────────────────

_log_file = open('flow.log', 'w')

def _log(agent, destination, msg):
    line = '─' * 62
    _log_file.write(line + '\n')
    _log_file.write(f' {agent}  →  {destination}\n')
    _log_file.write(line + '\n')
    skip = {'send_to'}
    for k, v in msg.items():
        if k in skip:
            continue
        v_str = str(v)
        if len(v_str) > 80:
            v_str = v_str[:77] + '...'
        _log_file.write(f' {k:<12} {v_str}\n')
    _log_file.write('\n')
    _log_file.flush()


# ── Role: filter ──────────────────────────────────────────────────────

_filter_prompt = "# Role: filter\n\nYou are a content filter who receives news articles and sends\narticles to a keeper or a discard.\n\nYour job is to decide if each article is about the americas: canada, usa, brazil, ..\nIf the article is about the americas, send to keeper.\nOtherwise send to discard.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: keeper, discard>\", \"text\": \"<content>\"}"
_filter_ai = ai_agent(_filter_prompt)

def filter_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _filter_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["keeper"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('filter', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[filter] Error: {e}")
        return []


# ── Sinks ────────────────────────────────────────────────────────────

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name="console_printer")

_jsonl_recorder = JSONLRecorder(path="filtered_output.jsonl")
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name="jsonl_recorder")


# ── Sources ──────────────────────────────────────────────────────────

_al_jazeera = al_jazeera(max_articles=2)
src_al_jazeera = Source(fn=_al_jazeera.run, name="al_jazeera")

_bbc_world = bbc_world(max_articles=2)
src_bbc_world = Source(fn=_bbc_world.run, name="bbc_world")


# ── Agents ───────────────────────────────────────────────────────────

Felix = Role(fn=filter_fn, statuses=["keeper", "discard"], name="Felix")


# ── Network ──────────────────────────────────────────────────────────

g = network([
    (src_al_jazeera, Felix),
    (src_bbc_world, Felix),
    (Felix.out_0, console_printer),  # keeper
    (Felix.out_1, jsonl_recorder),  # discard
])


if __name__ == "__main__":
    print()
    print("News Filter")
    print("=" * 60)
    print()
    g.run_network()
    _log_file.close()
    print()
    print("Done! Flow log written to flow.log")
    print()