"""Which skill version this release of dissyslab was built with.

Generated by ``scripts/stamp_skills.py``. Do not edit.

Why the package records this at all: skills install from the GitHub
repository and the library installs from PyPI, so the two arrive by
different roads and can disagree. The skill already refuses to describe
a package older than itself. This is the other direction -- it lets
``dsl doctor`` notice a skill *older* than the release and say so,
instead of leaving a student to compare two hash strings by eye.

Only the date half is compared. Between releases the repository's skill
is legitimately newer than the wheel expects, and a student who
installed it correctly must not be told they got it wrong.
"""

EXPECTED = {
    "backtest-strategy-builder": "2026-08-26.7a5ab88",
    "office-builder": "2026-08-26.3caa9fc",
    "sensor-office-builder": "2026-08-19.935f28d",
}
