# app.py — None
# Generated by office_compiler.py
# Run: python3 gallery/news_sentiment/newsroom/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent

from components.sinks.intelligence_display import IntelligenceDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder
import components.sources.rss_normalizer as rss_normalizer


# ── Role functions ───────────────────────────────────────

_analyst_agent = ai_agent('# Role: analyst\n\nYou are a senior news analyst who receives articles from global news sources.\n\nYour job is to assess whether each item is a significant world event worth\nmonitoring. Focus on the following topic categories:\n- Politics (especially US domestic and foreign policy)\n- Economics and financial markets\n- Diplomacy and international relations\n- Armed conflict and security\n- Climate and environment\n- Science and technology\n- Humanitarian crises and public health\n\nPrioritize stories that involve or directly affect the United States.\nGive extra weight to stories with significant US political, economic,\nor social implications even if they originate abroad.\n\nExclude celebrity gossip, sports, entertainment, lifestyle content,\nand personal opinion pieces with no broader significance.\n\nFor each relevant item, assign a significance rating:\nCRITICAL — breaking news requiring immediate attention\nHIGH — significant developments worth close monitoring\nMEDIUM — notable but not urgent\nLOW — background context or slow-moving developments\n\nIf the item is relevant, send to editor with your significance rating,\nthe topic category, and a one-sentence summary.\nIf the item is not relevant, send to discard.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: editor, discard>", "text": "<content>"}')

def _analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'editor')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[analyst] Error: {e}')
        return []

_editor_agent = ai_agent('# Role: editor\n\nYou are a senior editor who receives assessed articles from the analyst.\n\nYour job is to rewrite each article as a clean, structured news brief\nsuitable for a live intelligence display.\n\nYour output must include the following fields:\n- "headline": a clear, factual headline of no more than 12 words\n- "category": the topic category assigned by the analyst\n- "significance": the significance rating assigned by the analyst\n  (CRITICAL, HIGH, MEDIUM, or LOW)\n- "summary": two to three sentences covering what happened, who is involved,\n  and why it matters — with extra context on US relevance where applicable\n- "source": the original news outlet\n- "url": the original link to the article\n- "timestamp": the original publication timestamp\n- "text": repeat the summary here for display purposes\n\nCRITICAL and HIGH significance items must be clearly marked so they\nappear prominently in the live display.\n\nAlways send results to situation_room.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: situation_room>", "text": "<content>"}')

def _editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _editor_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'situation_room')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[editor] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Riley = Role(fn=_analyst_fn, statuses=['editor', 'discard'], name='Riley')
Morgan = Role(fn=_editor_fn, statuses=['situation_room'], name='Morgan')

_intelligence_display = IntelligenceDisplay(max_items=8)
intelligence_display = Sink(fn=_intelligence_display.run, name='intelligence_display')
_jsonl_recorder = JSONLRecorder(path='news_feed.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_al_jazeera = rss_normalizer.al_jazeera(max_articles=10, poll_interval=600)
al_jazeera = Source(fn=_al_jazeera.run, name='al_jazeera')
_bbc_world = rss_normalizer.bbc_world(max_articles=10, poll_interval=600)
bbc_world = Source(fn=_bbc_world.run, name='bbc_world')
_npr_news = rss_normalizer.npr_news(max_articles=10, poll_interval=600)
npr_news = Source(fn=_npr_news.run, name='npr_news')

# ── Network ──────────────────────────────────────────────

edges = [
    (al_jazeera, Riley),
    (bbc_world, Riley),
    (npr_news, Riley),
    (Riley.out_0, Morgan),
    (Riley.out_1, jsonl_recorder),
    (Morgan.out_0, intelligence_display),
    (Morgan.out_0, jsonl_recorder),
]

if __name__ == '__main__':
    print('🚀 Starting None...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
