"""Per-office synchronizer.

Auto-generated by
`dissyslab.patterns.sense_think_respond.build_office`.

Waits for one message on each of 3 named inports — urgency_classifier, sentiment_classifier, summarizer — dict-merges the messages,
and emits the merged article on `out`.
"""
from dissyslab.core import Agent
from dissyslab.office_v2 import AgentRoleEntry


class _Synchronizer(Agent):
    def __init__(self, name=None):
        super().__init__(
            name=name,
            inports=['urgency_classifier', 'sentiment_classifier', 'summarizer'],
            outports=["out_"],
        )

    def run(self) -> None:
        while True:
            merged: dict = {}
            for inport in self.inports:
                msg = self.recv(inport)
                if isinstance(msg, dict):
                    merged.update(msg)
            self.send(merged, "out_")


role = AgentRoleEntry(
    name="synchronizer",
    in_ports=('urgency_classifier', 'sentiment_classifier', 'summarizer',),
    out_ports=("out",),
    factory=_Synchronizer,
    description=(
        "Wait for one message on each of 3 inports — "
        "urgency_classifier, sentiment_classifier, summarizer — dict-merge, emit on out."
    ),
)
