# app.py — None
# Generated by office_compiler.py
# Run: python3 gallery/news_sentiment/sentiment_room/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent

from components.sinks.intelligence_display import IntelligenceDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder
from components.sources.bluesky_jetstream_source import BlueSkyJetstreamSource


# ── Role functions ───────────────────────────────────────

_sentiment_analyst_agent = ai_agent('# Role: sentiment_analyst\n\nYou are a sentiment analyst who receives matched news events and\ntheir associated BlueSky posts from the social listener.\n\nYour job is to produce a combined sentiment brief for each news event\nthat brings together the news details and the public reaction.\n\nYour output must include the following fields:\n- "headline": the headline of the news event\n- "category": the topic category of the news event\n- "significance": the significance rating (CRITICAL, HIGH, MEDIUM, LOW)\n- "summary": the two to three sentence news summary from the editor\n- "sentiment": the overall public mood — one of:\n    POSITIVE, NEGATIVE, MIXED, NEUTRAL, or LOW ENGAGEMENT\n  Use LOW ENGAGEMENT if the social listener flagged little public discussion\n- "sentiment_summary": two to three sentences describing what people\n  are saying, the dominant tone, and any notable divisions in opinion\n- "reactions": a list of up to 3 representative BlueSky posts,\n  each with the post text and the author handle\n- "source": the original news outlet\n- "url": the original article link\n- "timestamp": the original publication timestamp\n- "text": a single combined paragraph that reads naturally in a live display —\n  start with the news event, follow with what people are saying,\n  and close with the overall sentiment verdict\n\nCRITICAL and HIGH significance items must be clearly prioritized\nin the output so they surface first in the live display.\n\nAlways send results to pulse_room.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: pulse_room>", "text": "<content>"}')

def _sentiment_analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _sentiment_analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'pulse_room')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[sentiment_analyst] Error: {e}')
        return []

_social_listener_agent = ai_agent('# Role: social_listener\n\nYou are a social media listener who receives two types of input:\nstructured news briefs from the newsroom and live posts from BlueSky.\n\nYour job is to match live BlueSky posts to news events from the newsroom.\nFor each news event, find up to 3 BlueSky posts that are clearly\ndiscussing, reacting to, or commenting on that specific event.\n\nA BlueSky post is a match if it:\n- References the same event, people, or topic as the news brief\n- Was posted recently relative to the news event\n- Represents a genuine public reaction (not spam, bots, or unrelated content)\n\nPrioritize posts from or about US-based perspectives and reactions.\n\nIf a BlueSky post clearly matches a news event, send to sentiment_analyst\nwith the matched news brief and the post attached.\nIf a news event has very little or no matching social discussion,\nsend to sentiment_analyst anyway with a note that public engagement is low.\nIf a BlueSky post does not match any current news event, send to discard.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: sentiment_analyst, discard>", "text": "<content>"}')

def _social_listener_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _social_listener_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'sentiment_analyst')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[social_listener] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Jamie = Role(fn=_social_listener_fn, statuses=['sentiment_analyst', 'discard'], name='Jamie')
Alex = Role(fn=_sentiment_analyst_fn, statuses=['pulse_room'], name='Alex')

_intelligence_display = IntelligenceDisplay(max_items=8)
intelligence_display = Sink(fn=_intelligence_display.run, name='intelligence_display')
_jsonl_recorder = JSONLRecorder(path='sentiment_log.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_bluesky = BlueSkyJetstreamSource(max_posts=None, lifetime=None)
bluesky = Source(fn=_bluesky.run, name='bluesky')

# ── Network ──────────────────────────────────────────────

edges = [
    (bluesky, Jamie),
    (Jamie.out_0, Alex),
    (Jamie.out_1, jsonl_recorder),
    (Alex.out_0, intelligence_display),
    (Alex.out_0, jsonl_recorder),
]

if __name__ == '__main__':
    print('🚀 Starting None...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
