# app.py — None
# Generated by office_compiler.py
# Run: python3 gallery/new_grad_jobs/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent

from components.sinks.intelligence_display import IntelligenceDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder
import components.sources.rss_normalizer as rss_normalizer


# ── Role functions ───────────────────────────────────────

_formatter_agent = ai_agent('# Role: formatter\n\nYou are a job listing formatter who receives screened job postings from the screener.\n\nYour job is to rewrite each posting as a clean, scannable job brief.\n\nYour output must include the following fields:\n- "role": the job title\n- "company": the company name\n- "location": city and country, or "Remote" if fully remote\n- "type": one of Internship, New Grad, Entry-Level, or Junior\n- "tech": key technologies or languages mentioned (prioritize Python if present)\n- "text": a two to three sentence plain English summary of the role and what the company does\n- "flags": a list of notable highlights — include "Visa Sponsorship" if the posting\n  mentions sponsoring visas or work authorization, include "Remote-Friendly" if the\n  posting mentions remote or hybrid work options; leave empty if neither applies\n- "url": the original link to the posting\n- "source": the original source name\n- "timestamp": the original timestamp\n\nAlways send results to job_board.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: job_board>", "text": "<content>"}')

def _formatter_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _formatter_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'job_board')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[formatter] Error: {e}')
        return []

_screener_agent = ai_agent('# Role: screener\n\nYou are a job posting screener who receives articles and posts from tech news sources.\n\nYour job is to identify job postings that are relevant to entry-level candidates,\nnew graduates, or interns looking for work in Software Engineering, AI/ML, or Data Science,\nat companies located in or hiring in the United States or Canada.\n\nA posting is relevant if it meets ALL of the following:\n- It is a job posting or hiring announcement (not a news article, opinion, or discussion)\n- The role is in Software Engineering, Software Development, AI, Machine Learning,\n  Data Science, or a closely related technical field\n- The seniority level is entry-level, new grad, junior, associate, or intern\n  (if seniority is not mentioned, assume it may be entry-level and include it)\n- The position is located in the United States or Canada, or is fully remote\n  and open to US or Canada based applicants\n\nPrioritize postings that mention Python as a required or preferred skill.\n\nIf the posting meets all criteria, send to formatter with the original\nsource, url, timestamp, and author fields preserved.\nIf the posting does not meet all criteria, send to discard.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: formatter, discard>", "text": "<content>"}')

def _screener_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _screener_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'formatter')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[screener] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Jordan = Role(fn=_screener_fn, statuses=['formatter', 'discard'], name='Jordan')
Casey = Role(fn=_formatter_fn, statuses=['job_board'], name='Casey')

_intelligence_display = IntelligenceDisplay(max_items=8)
intelligence_display = Sink(fn=_intelligence_display.run, name='intelligence_display')
_jsonl_recorder = JSONLRecorder(path='jobs.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_hacker_news = rss_normalizer.hacker_news(max_articles=10, poll_interval=600)
hacker_news = Source(fn=_hacker_news.run, name='hacker_news')

# ── Network ──────────────────────────────────────────────

edges = [
    (hacker_news, Jordan),
    (Jordan.out_0, Casey),
    (Jordan.out_1, jsonl_recorder),
    (Casey.out_0, intelligence_display),
    (Casey.out_0, jsonl_recorder),
]

if __name__ == '__main__':
    print('🚀 Starting None...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
