"""Stale v1 artifact — remove with `git rm`.

This file was auto-generated by v1's ``dissyslab.office.make_office``,
which has been removed in the v2 cutover. The v2 build artifact is
``build/run.py``, generated by ``dsl build`` on the parent office.
Run this sub-office in v2 with::

    dsl run dissyslab/gallery/org_two_office_news/

(or build the parent and run the artifact at
``dissyslab/gallery/org_two_office_news/build/run.py``).
"""
raise ImportError(
    "This app.py is a stale v1 artifact. Use `dsl run` on the parent "
    "office (dissyslab/gallery/org_two_office_news/) instead."
)
