# dissyslab/gallery/.../roles/checker.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: CHECKER
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_checker_fn():
    _TEMP_THRESHOLD_F = 80.0
    _HUMIDITY_THRESHOLD_PCT = 60.0

    def checker_fn(msg):
        temp = msg["temp"]
        humidity = msg["humidity"]
        timestamp = msg.get("timestamp")
        if temp > _TEMP_THRESHOLD_F and humidity > _HUMIDITY_THRESHOLD_PCT:
            when = f" at {timestamp}" if timestamp else ""
            text = (
                f"ALERT: room too hot and humid{when} — "
                f"temperature {temp:.0f}°F (threshold {_TEMP_THRESHOLD_F:.0f}°F), "
                f"humidity {humidity:.0f}% (threshold {_HUMIDITY_THRESHOLD_PCT:.0f}%)."
            )
            return [({"temp": temp, "humidity": humidity, "timestamp": timestamp, "text": text}, "out")]
        return None

    return checker_fn


role = AgentRoleEntry(
    name='checker',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_checker_fn(), statuses=['out']),
)
