# dissyslab/gallery/.../roles/temp_sensor.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: TEMP_SENSOR
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_temp_sensor_fn():
    _READINGS = [70.0, 82.0, 79.0, 85.0]
    _TIMES = [
        "2026-07-20T10:00:00Z", "2026-07-20T10:01:00Z",
        "2026-07-20T10:02:00Z", "2026-07-20T10:03:00Z",
    ]

    def temp_sensor_fn(msg):
        return [({"temp": v, "timestamp": t}, "out") for v, t in zip(_READINGS, _TIMES)]

    return temp_sensor_fn


role = AgentRoleEntry(
    name='temp_sensor',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_temp_sensor_fn(), statuses=['out']),
)
