# app.py — AUTO-GENERATED by office_compiler.py
# Office: news_editorial
# Roles: editor, writer
#
# Routing:
#   al_jazeera  →  Susan
#   bbc_world  →  Susan
#   npr_news  →  Susan
#   Susan [copywriter]  →  Anna
#   Susan [archivist]  →  jsonl_recorder, console_printer
#   Anna [client]  →  Susan


import json
import re

from dissyslab import network
from dissyslab.blocks import Source, Sink
from dissyslab.blocks.role import Role
from dissyslab.components.transformers.ai_agent import ai_agent
from dissyslab.components.sources.rss_normalizer import al_jazeera, bbc_world, npr_news
from dissyslab.components.sinks.sink_jsonl_recorder import JSONLRecorder
from dissyslab.components.sinks.console_display import ConsoleDisplay


# ── Logging ──────────────────────────────────────────────────────────

_log_file = open('flow.log', 'w')

def _log(agent, destination, msg):
    line = '─' * 62
    _log_file.write(line + '\n')
    _log_file.write(f' {agent}  →  {destination}\n')
    _log_file.write(line + '\n')
    skip = {'send_to'}
    for k, v in msg.items():
        if k in skip:
            continue
        v_str = str(v)
        if len(v_str) > 80:
            v_str = v_str[:77] + '...'
        _log_file.write(f' {k:<12} {v_str}\n')
    _log_file.write('\n')
    _log_file.flush()


# ── Role: editor ──────────────────────────────────────────────────────

_editor_prompt = "# Role: editor\n\nYou are an editor who receives one message and responds\nby sending zero or more messages, each addressed to a destination role.\n\nThe messages you receive and send are either plain text or a document\npartitioned into sections, each with a section header and a section body.\nTreat a document as JSON with each section header as a key and the\nsection body as the corresponding value. Section headers are unique.\n\nYour job is to analyze the sentiment of each article and score it\nfrom 0.0 (most negative) to 1.0 (most positive).\n\nThe document has a section called \"rewrites\" whose value is a number.\nIf absent, treat as 0.\n\nIf the score is less than 0.25 or greater than 0.75, send to archivist.\nIf the score is between 0.25 and 0.75 and rewrites < 3, send to copywriter\nand increment rewrites by 1.\nIf the score is between 0.25 and 0.75 and rewrites >= 3, send to archivist.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: archivist, copywriter>\", \"text\": \"<content>\"}"
_editor_ai = ai_agent(_editor_prompt)

def editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _editor_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["archivist"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('editor', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[editor] Error: {e}")
        return []


# ── Role: writer ──────────────────────────────────────────────────────

_writer_prompt = "# Role: writer\n\nYou are a writer who receives one message and responds\nby sending zero or more messages, each addressed to a destination role.\n\nThe messages you receive and send are either plain text or a document\npartitioned into sections, each with a section header and a section body.\nTreat a document as JSON with each section header as a key and the\nsection body as the corresponding value. Section headers are unique.\n\nYour job is to rewrite the article to be more strongly opinionated \u2014\npush the sentiment either more positive or more negative, whichever\nrequires less change. Preserve all sections from the input document.\n\nAlways send to client.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: client>\", \"text\": \"<content>\"}"
_writer_ai = ai_agent(_writer_prompt)

def writer_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _writer_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["client"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('writer', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[writer] Error: {e}")
        return []


# ── Sinks ────────────────────────────────────────────────────────────

_jsonl_recorder = JSONLRecorder(path="editorial_output.jsonl")
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name="jsonl_recorder")

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name="console_printer")


# ── Sources ──────────────────────────────────────────────────────────

_al_jazeera = al_jazeera(max_articles=5)
src_al_jazeera = Source(fn=_al_jazeera.run, name="al_jazeera")

_bbc_world = bbc_world(max_articles=5)
src_bbc_world = Source(fn=_bbc_world.run, name="bbc_world")

_npr_news = npr_news(max_articles=5)
src_npr_news = Source(fn=_npr_news.run, name="npr_news")


# ── Agents ───────────────────────────────────────────────────────────

Susan = Role(fn=editor_fn, statuses=["archivist", "copywriter"], name="Susan")
Anna = Role(fn=writer_fn, statuses=["client"], name="Anna")


# ── Network ──────────────────────────────────────────────────────────

g = network([
    (src_al_jazeera, Susan),
    (src_bbc_world, Susan),
    (src_npr_news, Susan),
    (Susan.out_1, Anna),  # copywriter
    (Susan.out_0, jsonl_recorder),  # archivist
    (Susan.out_0, console_printer),  # archivist
    (Anna.out_0, Susan),  # client
])


if __name__ == "__main__":
    print()
    print("News Editorial")
    print("=" * 60)
    print()
    g.run_network()
    _log_file.close()
    print()
    print("Done! Flow log written to flow.log")
    print()