# app.py — stocks_monitor
# Generated by office_compiler.py
# Run: python3 gallery/stocks_monitor/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent

from components.sinks.console_display import ConsoleDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder
from components.sources.generated.stocks_source import StocksSource


# ── Role functions ───────────────────────────────────────

_analyst_agent = ai_agent('# Role: analyst\n\nYou are a financial analyst who receives stock price data.\n\nYour job is to write a concise one-sentence briefing describing\nthe current price, whether it is up or down, and whether any\naction or attention is warranted.\n\nAlways send to briefing.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: briefing>", "text": "<content>"}')

def _analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'briefing')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[analyst] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Alex = Role(fn=_analyst_fn, statuses=['briefing'], name='Alex')

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name='console_printer')
_jsonl_recorder = JSONLRecorder(path='stocks_monitor.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_stocks = StocksSource(ticker='AAPL', poll_interval=300)
stocks = Source(fn=_stocks.run, name='stocks')

# ── Network ──────────────────────────────────────────────

edges = [
    (stocks, Alex),
    (Alex.out_0, console_printer),
]

if __name__ == '__main__':
    print('🚀 Starting stocks_monitor...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
