# app.py — my_first_office
# Generated by office_compiler.py
# Run: python3 gallery/my_first_office/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent

from components.sinks.console_display import ConsoleDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder
import components.sources.rss_normalizer as rss_normalizer


# ── Role functions ───────────────────────────────────────

_analyst_agent = ai_agent('# Role: analyst\n\nYou are a news analyst who receives articles from news sources.\n\nYour job is to decide if each item is worth reading — something\na curious, informed person would find genuinely interesting or important.\n\nExclude press releases, sponsored content, listicles, and articles\nwith no real substance.\n\nIf the item is under one of these topics, send to editor.\nOtherwise send to discard.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: editor, discard>", "text": "<content>"}')

def _analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'editor')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[analyst] Error: {e}')
        return []

_editor_agent = ai_agent('# Role: editor\n\nYou are an editor who receives articles from the analyst.\n\nYour job is to rewrite each article as a single crisp sentence\nthat captures the key point — something you\'d say to a colleague\nin the hallway.\n\nRate each item\'s importance: HIGH, MEDIUM, or LOW.\nPut your rating in a field called "importance" and your\none-sentence summary in the "text" field.\n\nAlways send results to briefing.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: briefing>", "text": "<content>"}')

def _editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _editor_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'briefing')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[editor] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Alex = Role(fn=_analyst_fn, statuses=['editor', 'discard'], name='Alex')
Morgan = Role(fn=_editor_fn, statuses=['briefing'], name='Morgan')

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name='console_printer')
_jsonl_recorder = JSONLRecorder(path='my_first_office.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_hacker_news = rss_normalizer.hacker_news(max_articles=10, poll_interval=600)
hacker_news = Source(fn=_hacker_news.run, name='hacker_news')

# ── Network ──────────────────────────────────────────────

edges = [
    (hacker_news, Alex),
    (Alex.out_0, Morgan),
    (Alex.out_1, jsonl_recorder),
    (Morgan.out_0, console_printer),
    (Morgan.out_0, jsonl_recorder),
]

if __name__ == '__main__':
    print('🚀 Starting my_first_office...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
