# app.py — calendar_briefing
# Generated by office_compiler.py
# Run: python3 gallery/calendar_briefing/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dissyslab import network
from dissyslab.blocks import Source, Sink
from dissyslab.blocks.role import Role
from dissyslab.components.transformers.ai_agent import ai_agent

from dissyslab.components.sinks.console_display import ConsoleDisplay
from dissyslab.components.sinks.sink_jsonl_recorder import JSONLRecorder
from dissyslab.components.sources.calendar_source import CalendarSource


# ── Role functions ───────────────────────────────────────

_analyst_agent = ai_agent('# Role: analyst\n\nYou are a calendar assistant who receives upcoming calendar events.\n\nYour job is to write a concise one-sentence briefing for each event\ndescribing what it is, when it is, and where it is (if relevant).\n\nIf the event seems important or time-sensitive, note that.\n\nAlways send to briefing.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: briefing>", "text": "<content>"}')

def _analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'briefing')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[analyst] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Alex = Role(fn=_analyst_fn, statuses=['briefing'], name='Alex')

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name='console_printer')
_jsonl_recorder = JSONLRecorder(path='calendar_briefing.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_calendar = CalendarSource(poll_interval=300, days_ahead=7)
calendar = Source(fn=_calendar.run, name='calendar')

# ── Network ──────────────────────────────────────────────

edges = [
    (calendar, Alex),
    (Alex.out_0, console_printer),
]

if __name__ == '__main__':
    print('🚀 Starting calendar_briefing...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
