# app.py — AUTO-GENERATED by make_office.py
# Office: news_monitor
# Open office — import news_monitor to use in a larger network.
#
#   from gallery.org_two_office_news.news_monitor.app import news_monitor

import json

from dsl.composed_agent import composed_agent
from dsl.blocks import Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent
from components.sinks.discard import Discard

# ── Sinks ────────────────────────────────────────────────────────────

_discard = Discard()
discard = Sink(fn=_discard.run, name="discard")

# ── Role: analyst ─────────────────────────────────────────────────────

_analyst_prompt = "# Role: analyst\n\nYou are a news analyst who receives articles and sends\narticles either to an output or to discard.\n\nYour job is to assess the significance of each article and\nadd context. Add a \"significance\" field: CRITICAL, HIGH,\nMEDIUM, or LOW. Add a \"summary\" field: one sentence capturing\nthe core news. Preserve all existing fields.\n\nIf significance is CRITICAL, HIGH, or MEDIUM, send to output.\nOtherwise send to discard.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: output, discard>\", \"text\": \"<content>\"}"
_analyst_ai = ai_agent(_analyst_prompt)

def analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw         = _analyst_ai(text)
        result      = raw if isinstance(raw, dict) else json.loads(raw)
        out         = {**msg, **result}
        destination = result.get("send_to", "output")
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f"[analyst] Error: {e}")
        return []


# ── Role: correspondent ───────────────────────────────────────────────

_correspondent_prompt = "# Role: correspondent\n\nYou are a news correspondent who receives articles and sends\narticles to an analyst or a discard.\n\nYour job is to decide if each article is worth reporting on \u2014\ncovering significant world events: major political developments,\nconflicts, economic shifts, scientific breakthroughs, or\nnatural disasters.\n\nExclude celebrity gossip, entertainment news, sports, and\nopinion pieces with no broader significance.\n\nIf the article is worth reporting, send to analyst.\nOtherwise send to discard.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: analyst, discard>\", \"text\": \"<content>\"}"
_correspondent_ai = ai_agent(_correspondent_prompt)

def correspondent_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw         = _correspondent_ai(text)
        result      = raw if isinstance(raw, dict) else json.loads(raw)
        out         = {**msg, **result}
        destination = result.get("send_to", "analyst")
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f"[correspondent] Error: {e}")
        return []


# ── Agents ───────────────────────────────────────────────────────────

Alex = Role(
    fn=correspondent_fn,
    statuses=["analyst", "discard"],
    name="Alex",
)
Morgan = Role(
    fn=analyst_fn,
    statuses=["output", "discard"],
    name="Morgan",
)

# ── Composed Agent ───────────────────────────────────────────────────

news_monitor = composed_agent(
    name="news_monitor",
    inputs=["article_in"],
    outputs=["article_out"],
)

news_monitor.network = [
    (news_monitor.article_in, Alex),
    (Alex.out_0, Morgan),  # analyst
    (Alex.out_1, discard),  # discard
    (Morgan.out_0, news_monitor.article_out),  # output
    (Morgan.out_1, discard),  # discard
]
