# app.py — AUTO-GENERATED by office_compiler.py
# Office: news_chain
# Roles: editor, writer
#
# Routing:
#   al_jazeera  →  Susan
#   Susan [writer]  →  Anna
#   Anna [archivist]  →  console_printer


import json
import re

from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent
from components.sources.rss_normalizer import al_jazeera
from components.sinks.sink_jsonl_recorder import JSONLRecorder
from components.sinks.console_display import ConsoleDisplay


# ── Logging ──────────────────────────────────────────────────────────

_log_file = open('flow.log', 'w')

def _log(agent, destination, msg):
    line = '─' * 62
    _log_file.write(line + '\n')
    _log_file.write(f' {agent}  →  {destination}\n')
    _log_file.write(line + '\n')
    skip = {'send_to'}
    for k, v in msg.items():
        if k in skip:
            continue
        v_str = str(v)
        if len(v_str) > 80:
            v_str = v_str[:77] + '...'
        _log_file.write(f' {k:<12} {v_str}\n')
    _log_file.write('\n')
    _log_file.flush()


# ── Role: editor ──────────────────────────────────────────────────────

_editor_prompt = "# Role: editor\n\nYou are an editor who receives news articles and sends articles to a writer.\n\nYour job is to evaluate each article and add a brief editorial note\nexplaining what makes it newsworthy. Preserve all fields from the\ninput message.\n\nAlways send to writer.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: writer>\", \"text\": \"<content>\"}"
_editor_ai = ai_agent(_editor_prompt)

def editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _editor_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["writer"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('editor', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[editor] Error: {e}")
        return []


# ── Role: writer ──────────────────────────────────────────────────────

_writer_prompt = "# Role: writer\n\nYou are a writer who receives news articles and sends articles to an archivist.\n\nYour job is to rewrite the article headline to be more engaging and\nattention-grabbing. Preserve all other fields from the input message.\n\nAlways send to archivist.\n```\n\n**`gallery/org_news_chain/office.md`:**\n```\n# Office: news_chain\n\nSources: al_jazeera(max_articles=2)\nSinks: console_printer\n\nAgents:\nSusan is an editor.\nAnna is a writer.\n\nConnections:\nal_jazeera's destination is Susan.\nSusan's writer is Anna.\nAnna's archivist is console_printer.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: archivist>\", \"text\": \"<content>\"}"
_writer_ai = ai_agent(_writer_prompt)

def writer_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _writer_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["archivist"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('writer', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[writer] Error: {e}")
        return []


# ── Sinks ────────────────────────────────────────────────────────────

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name="console_printer")


# ── Sources ──────────────────────────────────────────────────────────

_al_jazeera = al_jazeera(max_articles=2)
src_al_jazeera = Source(fn=_al_jazeera.run, name="al_jazeera")


# ── Agents ───────────────────────────────────────────────────────────

Susan = Role(fn=editor_fn, statuses=["writer"], name="Susan")
Anna = Role(fn=writer_fn, statuses=["archivist"], name="Anna")


# ── Network ──────────────────────────────────────────────────────────

g = network([
    (src_al_jazeera, Susan),
    (Susan.out_0, Anna),  # writer
    (Anna.out_0, console_printer),  # archivist
])


if __name__ == "__main__":
    print()
    print("News Chain")
    print("=" * 60)
    print()
    g.run_network()
    _log_file.close()
    print()
    print("Done! Flow log written to flow.log")
    print()