# app.py — AUTO-GENERATED by office_compiler.py
# Office: situation_room
# Roles: analyst, editor
#
# Routing:
#   bluesky  →  Alex
#   al_jazeera  →  Alex
#   bbc_world  →  Alex
#   Alex [editor]  →  Morgan
#   Alex [discard]  →  jsonl_recorder
#   Morgan [situation_room]  →  intelligence_display, jsonl_recorder


import json
import re

from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent
from components.sources.rss_normalizer import al_jazeera, bbc_world
from components.sources.bluesky_jetstream_source import BlueSkyJetstreamSource
from components.sinks.intelligence_display import IntelligenceDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder


# ── Logging ──────────────────────────────────────────────────────────

_log_file = open('flow.log', 'w')

def _log(agent, destination, msg):
    line = '─' * 62
    _log_file.write(line + '\n')
    _log_file.write(f' {agent}  →  {destination}\n')
    _log_file.write(line + '\n')
    skip = {'send_to'}
    for k, v in msg.items():
        if k in skip:
            continue
        v_str = str(v)
        if len(v_str) > 80:
            v_str = v_str[:77] + '...'
        _log_file.write(f' {k:<12} {v_str}\n')
    _log_file.write('\n')
    _log_file.flush()


# ── Role: analyst ─────────────────────────────────────────────────────

_analyst_prompt = "# Role: analyst\n\nYou are a news analyst who receives posts and articles and sends\nitems to an editor or a discard.\n\nYour job is to decide if each item is relevant to significant\npolitical developments or economic events \u2014 specifically involving\ntopics such as Trump, Congress, Senate, elections, the Federal Reserve,\ntariffs, inflation, markets, Ukraine, Iran, trade policy, or the\nbroader economy.\n\nExclude celebrity gossip, sports, entertainment, and personal\nopinions with no broader political or economic significance.\n\nIf the item is relevant, send to editor.\nOtherwise send to discard.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: editor, discard>\", \"text\": \"<content>\"}"
_analyst_ai = ai_agent(_analyst_prompt)

def analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _analyst_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["editor"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('analyst', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[analyst] Error: {e}")
        return []


# ── Role: editor ──────────────────────────────────────────────────────

_editor_prompt = "# Role: editor\n\nYou are an editor who receives posts and articles and sends\nitems to a situation_room.\n\nYour job is to rate each item you receive for its significance\ngiving the item a significance rating of CRITICAL, HIGH, MEDIUM, or LOW.\nRewrite each item as a crisp one-paragraph briefing note beginning\nwith the significance rating.\nNote whether the item came from social media or news. Preserve the\nsource, url, timestamp, and author fields. Put your significance\nrating in a field called \"significance\" and your summary in the\n\"text\" field.\n\nAlways send results to situation_room.\n\nReturn JSON only, no explanation, no nested JSON:\n{\"send_to\": \"<one of: situation_room>\", \"text\": \"<content>\"}"
_editor_ai = ai_agent(_editor_prompt)

def editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw    = _editor_ai(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out    = {**msg, **result}
        destinations = result.get("send_to", ["situation_room"])
        if isinstance(destinations, str):
            destinations = [destinations]
        for dest in destinations:
            _log('editor', dest, out)
        return [(out, dest) for dest in destinations]
    except Exception as e:
        print(f"[editor] Error: {e}")
        return []


# ── Sinks ────────────────────────────────────────────────────────────

_intelligence_display = IntelligenceDisplay(max_items=8)
intelligence_display = Sink(fn=_intelligence_display.run, name="intelligence_display")

_jsonl_recorder = JSONLRecorder(path="situation_room.jsonl")
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name="jsonl_recorder")


# ── Sources ──────────────────────────────────────────────────────────

_bluesky = BlueSkyJetstreamSource(max_posts=None, lifetime=None)
src_bluesky = Source(fn=_bluesky.run, name="bluesky", interval=10)

_al_jazeera = al_jazeera(max_articles=10, poll_interval=600)
src_al_jazeera = Source(fn=_al_jazeera.run, name="al_jazeera")

_bbc_world = bbc_world(max_articles=10, poll_interval=600)
src_bbc_world = Source(fn=_bbc_world.run, name="bbc_world")


# ── Agents ───────────────────────────────────────────────────────────

Alex = Role(fn=analyst_fn, statuses=["editor", "discard"], name="Alex")
Morgan = Role(fn=editor_fn, statuses=["situation_room"], name="Morgan")


# ── Network ──────────────────────────────────────────────────────────

g = network([
    (src_bluesky, Alex),
    (src_al_jazeera, Alex),
    (src_bbc_world, Alex),
    (Alex.out_0, Morgan),  # editor
    (Alex.out_1, jsonl_recorder),  # discard
    (Morgan.out_0, intelligence_display),  # situation_room
    (Morgan.out_0, jsonl_recorder),  # situation_room
])


if __name__ == "__main__":
    print()
    print("Situation Room")
    print("=" * 60)
    print()
    g.run_network()
    _log_file.close()
    print()
    print("Done! Flow log written to flow.log")
    print()