# app.py — situation_room
# Generated by office_compiler.py
# Run: python3 gallery/org_situation_room/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent

from components.sinks.intelligence_display import IntelligenceDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder
from components.sources.bluesky_jetstream_source import BlueSkyJetstreamSource
import components.sources.rss_normalizer as rss_normalizer


# ── Role functions ───────────────────────────────────────

_analyst_agent = ai_agent('# Role: analyst\n\nYou are a news analyst who receives posts and articles and sends\nitems to an editor or a discard.\n\nYour job is to decide if each item is relevant to significant\npolitical developments or economic events — specifically involving\ntopics such as Trump, Congress, Senate, elections, the Federal Reserve,\ntariffs, inflation, markets, Ukraine, Iran, trade policy, or the\nbroader economy.\n\nExclude celebrity gossip, sports, entertainment, and personal\nopinions with no broader political or economic significance.\n\nIf the item is relevant, send to editor.\nOtherwise send to discard.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: editor, discard>", "text": "<content>"}')

def _analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'editor')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[analyst] Error: {e}')
        return []

_editor_agent = ai_agent('# Role: editor\n\nYou are an editor who receives posts and articles and sends\nitems to a situation_room.\n\nYour job is to rate each item you receive for its significance\ngiving the item a significance rating of CRITICAL, HIGH, MEDIUM, or LOW.\nRewrite each item as a crisp one-paragraph briefing note beginning\nwith the significance rating.\nNote whether the item came from social media or news. Preserve the\nsource, url, timestamp, and author fields. Put your significance\nrating in a field called "significance" and your summary in the\n"text" field.\n\nAlways send results to situation_room.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: situation_room>", "text": "<content>"}')

def _editor_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _editor_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'situation_room')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[editor] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Alex = Role(fn=_analyst_fn, statuses=['editor', 'discard'], name='Alex')
Morgan = Role(fn=_editor_fn, statuses=['situation_room'], name='Morgan')

_intelligence_display = IntelligenceDisplay(max_items=8)
intelligence_display = Sink(fn=_intelligence_display.run, name='intelligence_display')
_jsonl_recorder = JSONLRecorder(path='situation_room.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_bluesky = BlueSkyJetstreamSource(max_posts=None, lifetime=None)
bluesky = Source(fn=_bluesky.run, name='bluesky')
_al_jazeera = rss_normalizer.al_jazeera(max_articles=10, poll_interval=600)
al_jazeera = Source(fn=_al_jazeera.run, name='al_jazeera')
_bbc_world = rss_normalizer.bbc_world(max_articles=10, poll_interval=600)
bbc_world = Source(fn=_bbc_world.run, name='bbc_world')

# ── Network ──────────────────────────────────────────────

edges = [
    (bluesky, Alex),
    (al_jazeera, Alex),
    (bbc_world, Alex),
    (Alex.out_0, Morgan),
    (Alex.out_1, jsonl_recorder),
    (Morgan.out_0, intelligence_display),
    (Morgan.out_0, jsonl_recorder),
]

if __name__ == '__main__':
    print('🚀 Starting situation_room...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
