# dissyslab/gallery/.../roles/manifest.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: MANIFEST
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_manifest_fn():
    _EVENTS = [
        {"shipment_id": "S102"},
        {"shipment_id": "S101"},
        {"shipment_id": "S103"},
    ]

    def manifest_fn(msg):
        return [({"kind": "manifest", **e}, "out") for e in _EVENTS]

    return manifest_fn


role = AgentRoleEntry(
    name='manifest',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_manifest_fn(), statuses=['out']),
)
