# dissyslab/gallery/.../roles/match.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: MATCH
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_match_fn():
    pending = {}

    def match_fn(msg):
        kind = msg["kind"]
        sid = msg["shipment_id"]
        other_kind = "manifest" if kind == "scan" else "scan"
        slot = pending.setdefault(sid, {})
        if other_kind in slot:
            slot.pop(other_kind)
            if not slot:
                del pending[sid]
            print(f"[Match] shipment {sid}: both scan and manifest in -- releasing", flush=True)
            return [({"shipment_id": sid, "release": True}, "out")]
        slot[kind] = msg
        print(f"[Match] shipment {sid}: got {kind}, waiting on {other_kind}", flush=True)
        return None

    return match_fn


role = AgentRoleEntry(
    name='match',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_match_fn(), statuses=['out']),
)
