# dissyslab/gallery/.../roles/scan.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: SCAN
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_scan_fn():
    _EVENTS = [
        {"shipment_id": "S101"},
        {"shipment_id": "S103"},
        {"shipment_id": "S102"},
    ]

    def scan_fn(msg):
        return [({"kind": "scan", **e}, "out") for e in _EVENTS]

    return scan_fn


role = AgentRoleEntry(
    name='scan',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_scan_fn(), statuses=['out']),
)
