# dissyslab/gallery/.../roles/checker.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: CHECKER
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_checker_fn():
    def checker_fn(combined):
        temp = combined["temp"]
        hum = combined["humidity"]
        if temp > 80.0 and hum > 60.0:
            return [({"temp": temp, "humidity": hum, "alert": True}, "out")]
        return None
    return checker_fn


role = AgentRoleEntry(
    name='checker',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_checker_fn(), statuses=['out']),
)
