# dissyslab/gallery/.../roles/humidity_sensor.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: HUMIDITY_SENSOR
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_humidity_fn():
    _READINGS = [45.0, 65.0, 55.0, 70.0]
    def humidity_fn(msg):
        return [({"humidity": v}, "out") for v in _READINGS]
    return humidity_fn


role = AgentRoleEntry(
    name='humidity_sensor',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_humidity_fn(), statuses=['out']),
)
