# dissyslab/gallery/.../roles/temp_sensor.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: TEMP_SENSOR
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_temp_fn():
    _READINGS = [70.0, 82.0, 79.0, 85.0]
    def temp_fn(msg):
        return [({"temp": v}, "out") for v in _READINGS]
    return temp_fn


role = AgentRoleEntry(
    name='temp_sensor',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_temp_fn(), statuses=['out']),
)
