# app.py — gmail_monitor
# Generated by office_compiler.py
# Run: python3 gallery/gmail_monitor/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dissyslab import network
from dissyslab.blocks import Source, Sink
from dissyslab.blocks.role import Role
from dissyslab.components.transformers.ai_agent import ai_agent

from dissyslab.components.sinks.console_display import ConsoleDisplay
from dissyslab.components.sinks.sink_jsonl_recorder import JSONLRecorder
from dissyslab.components.sources.gmail_source import GmailSource


# ── Role functions ───────────────────────────────────────

_analyst_agent = ai_agent('# Role: analyst\n\nYou are an email analyst who receives emails from Gmail.\n\nYour job is to decide if each email is important and worth summarizing —\nsomething that requires attention or action, as opposed to newsletters,\npromotions, or automated notifications.\n\nIf the email is important, write a one-sentence summary of what it is\nabout and what action if any is needed. Send to summary.\n\nIf the email is not important, send to discard.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: summary, discard>", "text": "<content>"}')

def _analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'summary')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[analyst] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Alex = Role(fn=_analyst_fn, statuses=['summary', 'discard'], name='Alex')

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name='console_printer')
_jsonl_recorder = JSONLRecorder(path='gmail_monitor.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_gmail = GmailSource(poll_interval=60, max_emails=5, unread_only=True)
gmail = Source(fn=_gmail.run, name='gmail')

# ── Network ──────────────────────────────────────────────

edges = [
    (gmail, Alex),
    (Alex.out_0, console_printer),
    (Alex.out_1, jsonl_recorder),
]

if __name__ == '__main__':
    print('🚀 Starting gmail_monitor...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
