# app.py — web_monitor
# Generated by office_compiler.py
# Run: python3 gallery/web_monitor/app.py
#
# Edit your role or office files and recompile to regenerate.

import json
from dsl import network
from dsl.blocks import Source, Sink
from dsl.blocks.role import Role
from components.transformers.ai_agent import ai_agent

from components.sinks.console_display import ConsoleDisplay
from components.sinks.sink_jsonl_recorder import JSONLRecorder
from components.sources.mcp_source import MCPSource


# ── Role functions ───────────────────────────────────────

_analyst_agent = ai_agent('# Role: analyst\n\nYou are a news analyst who receives web page content fetched from URLs.\n\nYour job is to extract the key information from the content and decide\nif it contains anything newsworthy or interesting — new announcements,\nproduct launches, research findings, or significant updates.\n\nIf the content contains something worth noting, write a concise\none-paragraph summary of the most important point and send to summary.\n\nIf the content contains nothing newsworthy, send to discard.\\n\\nReturn JSON only, no explanation, no nested JSON:\\n{"send_to": "<one of: summary, discard>", "text": "<content>"}')

def _analyst_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw = _analyst_agent(text)
        result = raw if isinstance(raw, dict) else json.loads(raw)
        out = {**msg, **result}
        destination = result.get('send_to', 'summary')
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f'[analyst] Error: {e}')
        return []


# ── Nodes ────────────────────────────────────────────────

Alex = Role(fn=_analyst_fn, statuses=['summary', 'discard'], name='Alex')

_console_printer = ConsoleDisplay()
console_printer = Sink(fn=_console_printer.run, name='console_printer')
_jsonl_recorder = JSONLRecorder(path='web_monitor.jsonl')
jsonl_recorder = Sink(fn=_jsonl_recorder.run, name='jsonl_recorder')

_web = MCPSource(server='fetch', tool='fetch', args={'url': 'https://www.anthropic.com/news'}, poll_interval=300, max_items=3)
web = Source(fn=_web.run, name='web')

# ── Network ──────────────────────────────────────────────

edges = [
    (web, Alex),
    (Alex.out_0, console_printer),
    (Alex.out_1, jsonl_recorder),
]

if __name__ == '__main__':
    print('🚀 Starting web_monitor...')
    print('   Press Ctrl+C to stop.')
    print('━' * 60)
    print()
    g = network(edges)
    g.run_network()
