# dissyslab/gallery/.../roles/clerk.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: CLERK
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_clerk_fn():
    pending = {}

    def clerk_fn(msg):
        if "approved" in msg:
            ticket = pending.pop("current")
            outcome = {
                "ticket_id": msg["ticket_id"],
                "customer": ticket["customer"],
                "amount": ticket["amount"],
                "approved": msg["approved"],
                "decided_by": "manager",
            }
            print(f"[Clerk] manager decided ticket {msg['ticket_id']}: approved={msg['approved']}", flush=True)
            return [
                (outcome, "to_log"),
                ({"next": "ticket"}, "command"),
            ]
        if msg["amount"] < 50:
            outcome = {
                "ticket_id": msg["ticket_id"],
                "customer": msg["customer"],
                "amount": msg["amount"],
                "approved": True,
                "decided_by": "clerk",
            }
            print(f"[Clerk] ticket {msg['ticket_id']} (${msg['amount']}) -- approved on the spot", flush=True)
            return [
                (outcome, "to_log"),
                ({"next": "ticket"}, "command"),
            ]
        pending["current"] = dict(msg)
        print(f"[Clerk] ticket {msg['ticket_id']} (${msg['amount']}) -- escalating to manager, freezing", flush=True)
        return [
            (dict(msg), "to_manager"),
            ({"next": "manager_reply"}, "command"),
        ]

    return clerk_fn


role = AgentRoleEntry(
    name='clerk',
    in_ports=("in_",),
    out_ports=('to_manager', 'to_log', 'command'),
    factory=lambda: Role(fn=_make_clerk_fn(), statuses=['to_manager', 'to_log', 'command']),
)
