# dissyslab/gallery/.../roles/manager.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: MANAGER
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_manager_fn():
    def manager_fn(msg):
        print(f"[Manager] reviewing ticket {msg['ticket_id']} (${msg['amount']}) -- approving", flush=True)
        return [({"ticket_id": msg["ticket_id"], "approved": True}, "out")]

    return manager_fn


role = AgentRoleEntry(
    name='manager',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_manager_fn(), statuses=['out']),
)
