# dissyslab/gallery/.../roles/tickets.py
"""Generated by from_officespeak.py from an approved Phase 2 body.
Agent: TICKETS
"""

from __future__ import annotations

from typing import Any

from dissyslab.blocks.role import Role
from dissyslab.office.library import AgentRoleEntry

def _make_tickets_fn():
    _TICKETS = [
        {"ticket_id": "T1", "customer": "Ana", "amount": 20, "item": "book", "reason": "wrong item"},
        {"ticket_id": "T2", "customer": "Ben", "amount": 120, "item": "chair", "reason": "damaged"},
        {"ticket_id": "T3", "customer": "Cy", "amount": 35, "item": "lamp", "reason": "changed mind"},
        {"ticket_id": "T4", "customer": "Dee", "amount": 80, "item": "monitor", "reason": "defective"},
    ]

    def tickets_fn(msg):
        return [(dict(t), "out") for t in _TICKETS]

    return tickets_fn


role = AgentRoleEntry(
    name='tickets',
    in_ports=("in_",),
    out_ports=('out',),
    factory=lambda: Role(fn=_make_tickets_fn(), statuses=['out']),
)
