# dissyslab/office/make_office.py
#
# Compiles an open office into app.py — a Python file exporting
# a composed_agent instance importable by larger networks.
#
# An open office has Inputs and Outputs declared in office.md.
# It is a composable black box, not a standalone runnable network.
#
# Usage (preferred):
#   dsl build gallery/org_two_office_news/news_monitor/
#
# Equivalent:
#   python -m dissyslab.office.make_office <office_dir>
#
# For closed (runnable) offices, use `dsl run` instead.

import sys
import json
from pathlib import Path
from string import Template

from dissyslab.office.utils import (
    SOURCE_REGISTRY,
    SINK_REGISTRY,
    parse_roles,
    parse_office,
    validate,
    show_routing_table,
)


# ── Template ──────────────────────────────────────────────────────────────────

APP_TEMPLATE = Template('''\
# app.py — AUTO-GENERATED by make_office.py
# Office: $office_name
# Open office — import $office_name to use in a larger network.
#
#   from $dotted_path.app import $office_name

import json

from dissyslab.composed_agent import composed_agent
from dissyslab.blocks import Sink
from dissyslab.blocks.role import Role
from dissyslab.components.transformers.ai_agent import ai_agent
$extra_imports

$sink_block
$role_blocks
# ── Agents $agent_line_fill

$agent_block

# ── Composed Agent $composed_line_fill

$office_name = composed_agent(
    name="$office_name",
    inputs=$inputs,
    outputs=$outputs,
)

$office_name.network = [
$edge_block
]
''')


# ── Block builders ────────────────────────────────────────────────────────────

def _make_extra_imports(office):
    """Build import lines for RSS sources, BlueSky, and sinks."""
    lines = []
    rss_sources = [
        s["name"] for s in office["sources"]
        if SOURCE_REGISTRY.get(s["name"], {}).get("type") == "rss"
    ]
    if rss_sources:
        lines.append(
            "from dissyslab.components.sources.rss_normalizer import " +
            ", ".join(rss_sources)
        )
    for s in office["sources"]:
        if SOURCE_REGISTRY.get(s["name"], {}).get("type") == "bluesky":
            lines.append(SOURCE_REGISTRY[s["name"]]["import"])
    for s in office["sinks"]:
        lines.append(SINK_REGISTRY[s["name"]]["import"])
    return "\n".join(lines)


def _make_sink_block(office):
    """Build sink node instantiation lines."""
    if not office["sinks"]:
        return ""
    lines = ["# ── Sinks " + "─" * 60, ""]
    for sink in office["sinks"]:
        name = sink["name"]
        args = sink["args"]
        reg = SINK_REGISTRY[name]
        if reg["args"] == "named" and args:
            arg_str = ", ".join(
                f'{k}="{v}"' if isinstance(v, str) else f"{k}={v}"
                for k, v in args.items()
            )
            init = f'{reg["class"]}({arg_str})'
        else:
            init = f'{reg["class"]}()'
        lines.append(f'_{name} = {init}')
        lines.append(f'{name} = Sink(fn=_{name}.{reg["call"]}, name="{name}")')
        lines.append("")
    return "\n".join(lines)


def _make_role_blocks(roles, office_path):
    """Build one role function per role."""
    blocks = []
    for role_name, role in roles.items():
        role_text = open(office_path / "roles" / f"{role_name}.md").read()
        valid_dests = role["sends_to"]
        default_dest = valid_dests[0]
        options = ", ".join(valid_dests)
        contract = f'\nReturn JSON only, no explanation, no nested JSON:\n{{"send_to": "<one of: {options}>", "text": "<content>"}}'
        prompt = role_text.strip() + "\n" + contract
        fill = "─" * (60 - len(role_name))

        role_tmpl = Template('''\
# ── Role: $role_name $fill

_${role_name}_prompt = $prompt_json
_${role_name}_ai = ai_agent(_${role_name}_prompt)

def ${role_name}_fn(msg):
    text = json.dumps(msg) if isinstance(msg, dict) else str(msg)
    try:
        raw         = _${role_name}_ai(text)
        result      = raw if isinstance(raw, dict) else json.loads(raw)
        out         = {**msg, **result}
        destination = result.get("send_to", "$default_dest")
        if isinstance(destination, list):
            return [(out, dest) for dest in destination]
        return [(out, destination)]
    except Exception as e:
        print(f"[$role_name] Error: {e}")
        return []

''')
        blocks.append(role_tmpl.substitute(
            role_name=role_name,
            fill=fill,
            prompt_json=json.dumps(prompt),
            default_dest=default_dest,
        ))
    return "\n".join(blocks)


def _make_agent_block(roles, office):
    """Build Role node instantiation lines."""
    lines = []
    for agent in office["agents"]:
        agent_name = agent["name"]
        role_name = agent["role"]
        lines.append(f'{agent_name} = Role(')
        lines.append(f'    fn={role_name}_fn,')
        lines.append(
            f'    statuses={json.dumps(roles[role_name]["sends_to"])},')
        lines.append(f'    name="{agent_name}",')
        lines.append(')')
    return "\n".join(lines)


def _make_edge_block(roles, office, office_name):
    """Build composed_agent.network edge lines."""
    known_agents = {a["name"] for a in office["agents"]}
    known_outputs = set(office["outputs"])
    inputs = set(office["inputs"])

    port_index = {
        role_name: {dest: i for i, dest in enumerate(role["sends_to"])}
        for role_name, role in roles.items()
    }

    lines = []

    # Input port → first agent
    for conn in office["connections"]:
        sender = conn["from"]
        if conn["destination"] == "destination" and sender in inputs:
            lines.append(f"    ({office_name}.{sender}, {conn['to'][0]}),")

    # Agent → agent, sink, or output port
    for conn in office["connections"]:
        sender = conn["from"]
        dest_name = conn["destination"]
        if dest_name == "destination" or sender not in known_agents:
            continue
        agent = next(a for a in office["agents"] if a["name"] == sender)
        role_name = agent["role"]
        idx = port_index[role_name].get(dest_name)
        if idx is None:
            continue
        for to in conn["to"]:
            if to in known_outputs:
                lines.append(
                    f"    ({sender}.out_{idx}, {office_name}.{to}),  # {dest_name}"
                )
            else:
                lines.append(
                    f"    ({sender}.out_{idx}, {to}),  # {dest_name}"
                )

    return "\n".join(lines)


# ── Write app.py ──────────────────────────────────────────────────────────────

def write_app(roles, office, office_dir):
    """
    Write app.py for an open office.
    Exports a composed_agent instance with named inports and outports.
    """
    office_path = Path(office_dir).resolve()
    app_path = office_path / "app.py"
    office_name = office["office_name"]
    inputs = office["inputs"]
    outputs = office["outputs"]

    rel_path = office_path.relative_to(Path.cwd())
    dotted_path = ".".join(rel_path.parts)

    content = APP_TEMPLATE.substitute(
        office_name=office_name,
        dotted_path=dotted_path,
        extra_imports=_make_extra_imports(office),
        sink_block=_make_sink_block(office),
        role_blocks=_make_role_blocks(roles, office_path),
        agent_line_fill="─" * 59,
        agent_block=_make_agent_block(roles, office),
        composed_line_fill="─" * 51,
        inputs=json.dumps(inputs),
        outputs=json.dumps(outputs),
        edge_block=_make_edge_block(roles, office, office_name),
    )

    app_path.write_text(content)
    print(f"  ✓ Written to {app_path}")
    print()
    print(f"  Import with:")
    print(f"    from {dotted_path}.app import {office_name}")


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: dsl build <office_dir>")
        print("   or: python -m dissyslab.office.make_office <office_dir>")
        sys.exit(1)

    office_dir = sys.argv[1]

    print()
    print("Parsing roles...")
    roles = parse_roles(office_dir)

    print()
    print("Parsing office...")
    office = parse_office(office_dir)

    if not (office["inputs"] or office["outputs"]):
        print()
        print("Error: this is a closed office (no Inputs/Outputs).")
        print("Use `dsl run` instead:")
        print(f"  dsl run {office_dir}")
        sys.exit(1)

    print()
    print("Validating...")
    errors = validate(roles, office)
    if errors:
        print("Errors found:")
        for e in errors:
            print(f"  ✗ {e}")
        sys.exit(1)
    print("  ✓ All checks passed.")

    show_routing_table(roles, office)

    answer = input("Does this look right? (yes / no): ").strip().lower()
    if answer != "yes":
        print()
        print("Edit your role or office files and run the compiler again.")
        sys.exit(0)

    print()
    print("Generating app.py...")
    write_app(roles, office, office_dir)
